### ISSUE TITLE
Sikre at build overholder KIT's 'good citizen' guide lines

### ISSUE THREAD

**Issue by rak-randers** [Randers-Kommune-Digitalisering/python-app-template#16]
```[tasklist]
### Tasks
- [x] Ændre app(flask/wsgi) logger til at skrive til stdout
- [x] numeric-user
- [x] Sikre at kan skaleres horizontalt, flere replicas
- [x] Deploy med version 1.33.12 af service helm chart (tester at den overholder 'good citizen')
```
